set @norm = 1;
UPDATE churn_users cu, posts p SET gap1 = p.gap_from_prev WHERE post_seq = 1 and cu.uid = p.owneruserid and cu.k = 1;
select @norm;
UPDATE churn_users cu, posts p SET gap2 = p.gap_from_prev WHERE post_seq = 2 and cu.uid = p.owneruserid and cu.k = 2;
select @norm;
UPDATE churn_users cu, posts p SET gap3 = p.gap_from_prev WHERE post_seq = 3 and cu.uid = p.owneruserid and cu.k = 3;
select @norm;
UPDATE churn_users cu, posts p SET gap4 = p.gap_from_prev WHERE post_seq = 4 and cu.uid = p.owneruserid and cu.k = 4;
select @norm;
UPDATE churn_users cu, posts p SET gap5 = p.gap_from_prev WHERE post_seq = 5 and cu.uid = p.owneruserid and cu.k = 5;
select @norm;
UPDATE churn_users cu, posts p SET gap6 = p.gap_from_prev WHERE post_seq = 6 and cu.uid = p.owneruserid and cu.k = 6;
select @norm;
UPDATE churn_users cu, posts p SET gap7 = p.gap_from_prev WHERE post_seq = 7 and cu.uid = p.owneruserid and cu.k = 7;
select @norm;
UPDATE churn_users cu, posts p SET gap8 = p.gap_from_prev WHERE post_seq = 8 and cu.uid = p.owneruserid and cu.k = 8;
select @norm;
UPDATE churn_users cu, posts p SET gap9 = p.gap_from_prev WHERE post_seq = 9 and cu.uid = p.owneruserid and cu.k = 9;
select @norm;
UPDATE churn_users cu, posts p SET gap10 = p.gap_from_prev WHERE post_seq = 10 and cu.uid = p.owneruserid and cu.k = 10;
select @norm;
UPDATE churn_users cu, posts p SET gap11 = p.gap_from_prev WHERE post_seq = 11 and cu.uid = p.owneruserid and cu.k = 11;
select @norm;
UPDATE churn_users cu, posts p SET gap12 = p.gap_from_prev WHERE post_seq = 12 and cu.uid = p.owneruserid and cu.k = 12;
select @norm;
UPDATE churn_users cu, posts p SET gap13 = p.gap_from_prev WHERE post_seq = 13 and cu.uid = p.owneruserid and cu.k = 13;
select @norm;
UPDATE churn_users cu, posts p SET gap14 = p.gap_from_prev WHERE post_seq = 14 and cu.uid = p.owneruserid and cu.k = 14;
select @norm;
UPDATE churn_users cu, posts p SET gap15 = p.gap_from_prev WHERE post_seq = 15 and cu.uid = p.owneruserid and cu.k = 15;
select @norm;
UPDATE churn_users cu, posts p SET gap16 = p.gap_from_prev WHERE post_seq = 16 and cu.uid = p.owneruserid and cu.k = 16;
select @norm;
UPDATE churn_users cu, posts p SET gap17 = p.gap_from_prev WHERE post_seq = 17 and cu.uid = p.owneruserid and cu.k = 17;
select @norm;
UPDATE churn_users cu, posts p SET gap18 = p.gap_from_prev WHERE post_seq = 18 and cu.uid = p.owneruserid and cu.k = 18;
select @norm;
UPDATE churn_users cu, posts p SET gap19 = p.gap_from_prev WHERE post_seq = 19 and cu.uid = p.owneruserid and cu.k = 19;
select @norm;
UPDATE churn_users cu, posts p SET gap20 = p.gap_from_prev WHERE post_seq = 20 and cu.uid = p.owneruserid and cu.k = 20;
select @norm;
